name: freedefense
description: tower defense game

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/weapon/
    - assets/images/enemy/
    - assets/images/neutual/
    - assets/images/
    - assets/weaponParams.json
    - assets/enemyParams.json
